### ISSUE TITLE
Intermittent connection errors

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#75] opened 2016-05-11 19:42 UTC
We intermittently die with `java.net.ConnectException: failed to connect` in tests, can we fix/reproduce? 

Example: https://travis-ci.org/mediachain/mediachain/jobs/128964692

Does reconnect logic fix it?

Once this is resolved we can revert c51fb6e00396ea431d27573597bfe97f8cb7cd3a so transactor builds don't get a free pass.

**Comment by parkan** [comment] 2016-05-11 20:04
Also now seeing "executor not accepting a task" instead/in addition to this:

https://travis-ci.org/mediachain/mediachain/jobs/129520597

I think you saw all these just want to get the errors in one place. A possibly related behavior is that as of today the server doesn't seem to stop after tests complete

**Comment by vyzo** [comment] 2016-05-12 06:48
Not sure if the illegal state exception is related to the problem, as it appears to happen after shutdown.
The problem we are seeing in the failing test is connection errors or dropped connectiond.
Perhaps we can simply add some delays in the test?

**Comment by vyzo** [comment] 2016-05-12 06:50
thinking a little more about the IllegalStateException, perhaps it is caused by not having enough threads in the client pool -- client constructor configures it with 2.

**Comment by vyzo** [comment] 2016-05-12 06:51
The server not stopping is definitely the most worrisome of all.

**Comment by vyzo** [comment] 2016-05-12 07:35
Further digging in the logs, the IllegalStateExceptions seem to be shutdown related.
It seems that the netty transport is not cleanly shutdown.

**Comment by vyzo** [comment] 2016-05-12 07:37
It seems that the Reconnect recovery strategy has triggered the IllegalStateExceptions on connection close.
This sounds like a copycat issue to me.

**Comment by vyzo** [comment] 2016-05-12 07:45
I think that the recovery strategy is not transparent to requests in progress, so requests in flight are failed during reconnection.

**Comment by vyzo** [comment] 2016-05-12 09:27
#77 adds back-off retry logic in all client operations to recover from transient failures

**Comment by vyzo** [comment] 2016-05-12 09:48
verified that backoff-retry logic correctly kicks in, waiting for builds with bumped timeouts.

**Comment by vyzo** [comment] 2016-05-12 09:58
So here is the backoff kicking in:
https://travis-ci.org/mediachain/mediachain/jobs/129661654 [see the failed test]
It seems that 30sec timeouts are still inadequate.

**Comment by vyzo** [comment] 2016-05-12 10:21
Here is an additional data point:
https://travis-ci.org/mediachain/mediachain/jobs/129666090

In this case the retry logic appears to be failing correlated with IllegalStateExceptions. Perhaps there is a connection with those after all.

**Comment by vyzo** [comment] 2016-05-12 10:28
increasing the number of threads in client's netty doesn't do anything for the IllegalStateExceptions.

**Comment by vyzo** [comment] 2016-05-12 11:11
it appears that the copycat client session recovery mechanism is broken.

**Comment by vyzo** [comment] 2016-05-12 11:13
Indeed, removing the recovery strategy parameter from the client build makes the IllegalStateExceptions go away.

**Comment by vyzo** [comment] 2016-05-12 11:50
so I checked with a custom recovery strategy and was able to reproduce the IllegalStateException with a recovery strategy that simply calls recover on the client.
It appears that when the client is closed externally, the recovery strategy is erroneously invoked.
The IllegalStateException results from the call to recover.

So traced the origin of IllegalStateException and confirmed that the recovery strategies are broken on shutdown.

**Comment by vyzo** [comment] 2016-05-12 12:28
So Roll Your Own recovery in #77 appears to work:
https://travis-ci.org/mediachain/mediachain/jobs/129693055

Notice the connection errors, the operation retry and the session recovery.

**Comment by vyzo** [comment] 2016-05-12 12:35
And here:
https://travis-ci.org/mediachain/mediachain/jobs/129693060

Here we have a failure in the last check, with apparently not all clients receiving the same block events.
This is not surprising given that there were intermittent connectivity errors in this trace.

**Comment by vyzo** [comment] 2016-05-12 13:04
We still have the occasional timeout and missed block event in the JournalClusterSpec test.
The situation has definitely improved however, as we have a working recovery strategy for intermittent failures and connectivity loss.

I don't think that the cluster test is completely fixable because there is always the possibility of a missed event during connectivity loss, and the CI build seems to trigger worst case conditions for the cluster.

**Comment by vyzo** [comment] 2016-05-12 13:06
to be clear, the intermittent failures seem to be happening in the mediachain part of the testsuite now, the transactor test suite seems to be ok.

**Comment by vyzo** [comment] 2016-05-12 13:34
A couple more datapoints:
https://travis-ci.org/mediachain/mediachain/builds/129701528
https://travis-ci.org/mediachain/mediachain/builds/129701505

The transactor tests pass, but the aggregate mediachain test fails with timing issues.

**Comment by vyzo** [comment] 2016-05-13 07:57
With the changes in tip of #77 the retry and reconnect logic is robust:
https://travis-ci.org/mediachain/mediachain/builds/129928773
https://travis-ci.org/mediachain/mediachain/builds/129928782

We do have the problem of missed events however, which makes tests that check the event delivery mechanisms to fail under load in the mediachain aggregate test.
But this is now a byproduct of the test environment, as the underlying problems with client reliability and failure recovery have been fixed.

I propose that transactor can be revoked of its free pass, but we should have a pass on the mediachain test since the extreme load conditions make some sessions temporary disconnect and lose commit events.

**Comment by vyzo** [comment] 2016-05-13 08:33
There is another intermittent problem that rears its ugly head sometimes: a cluster member may be stuck polling other (defunct) members and not shutting down.
This is something that happens deep in the bowels of the copycat server implementation, not sure if there is anything we can do about it.

**Comment by vyzo** [comment] 2016-05-13 08:36
So no matter what we do, there are circumstances where the transactor test suite can fail in the CI environment.
Perhaps transactor should return its pass indefinitely after all, and keep an eye for the case of new errors appearing: basically use the CI environment as a stress tester for copycat.

**Comment by vyzo** [comment] 2016-05-13 08:42
Anyhow, I think that the root problems of the Issue (Connection errors and the IllegalStateException) have been addressed in #77

Proposed Resolution for the test strategy:
- no free pass for transactor; check the occasional CI failure to be a missed event or timeout.
- free pass to the aggregate mediachain test, as its load characteristics aggrovate intermittent failures with timeouts and missed events, which lead the suite to frequently fail.

**Comment by vyzo** [comment] 2016-05-13 08:55
Opened #79 for the intermittent limbo problem.

**Comment by vyzo** [comment] 2016-05-13 16:23
#77 has been merged and transactor voucher revoked, closing.

**Closed as completed by vyzo** 2016-05-13 16:23 UTC

**Comment by parkan** [comment] 2016-05-13 16:26
Great investigative work, overall. I wonder what they saw in terms of these errors in https://github.com/atomix/atomix-jepsen

**Comment by vyzo** [comment] 2016-05-13 16:31
to be fair, they do say in their documentation that submitting operations while the session is suspended does not have any consistency guarantees.
