### ISSUE TITLE
gRPC connection trouble

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#129] opened 2016-06-14 20:08 UTC
Intermittent connection/cancellation exceptions, sometimes following a call, sometimes spontaneous.

Not reproducible with client + server on dev machine.

Possibly reproducible with server in vargrant VM.

Could be due to installing gRPC python plugin from master?

**Comment by yusefnapora** [comment] 2016-06-14 20:19
log / stacktrace (from the TransactorService running in an sbt repl session):

```
Jun 14, 2016 4:05:33 PM io.grpc.netty.NettyServerHandler onConnectionError
WARNING: Connection Error
io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 0000040800
    at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:82)
    at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:300)
    at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:209)
    at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:391)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:527)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:484)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:398)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:370)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
    at java.lang.Thread.run(Thread.java:745)

Jun 14, 2016 4:05:33 PM io.grpc.netty.NettyServerTransport notifyTerminated
SEVERE: Transport failed
io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 0000040800
    at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:82)
    at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:300)
    at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:209)
    at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:391)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:527)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:484)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:398)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:370)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
    at java.lang.Thread.run(Thread.java:745)
```

So far, I can reproduce this on an ad-hoc setup ubuntu vm, with the grpc python plugin compiled from master, connecting to a transactor on the same vm.

I haven't been able to reproduce with the transactor running in a vagrant box and the python clients (indexer and mediachain-cli) running on my host mac.  

I think my mac's grpc-python-plugin was compiled from a checkout of the `release-0_14_1` tag; that's what's checked out now.  I'm not 100% on that; it's possible I compiled it against a different commit and checked out that tag for some other reason.  But either way, I definitely compiled it a few weeks ago, and it's possible that there's been a breaking change since.

I think I'm going to leave my ad-hoc vm alone, since it's the most "reliably broken" environment I have at the moment :)

The plan right now is to get the python clients running in a vagrant box with grpc from master and see if I can reproduce the bug.  If so, I'll try checking out the `release-0_14_1` tag and see if the problem goes away.

**Comment by parkan** [comment] 2016-06-14 20:46
Tried reading the grpc commit log and eyes glazed over a bit. We should def not be installing from master for sanity's sake, let's see if building from the tag helps

**Comment by yusefnapora** [comment] 2016-06-14 21:43
After mucking about a little with vagrant and python, etc, I decided the fastest way to check this is to just take a snapshot of my ad-hoc vm and try rebuilding grpc from the tag there.

So far I've tried the `release-0_14_1` and `release-0_14_0` tags, (regenerating the python protobuf code after each install), but I still get crashes 😞 

The crash doesn't seem to depend on the indexer; I can get it to crash with just this, without the indexer running:

``` bash
while true; do 
  mediachain -s localhost -p 10001 -e http://localhost:8000 ingest ../datasets/getty_custom/
done
```

after about a dozen imports it'll crash...

**Comment by parkan** [comment] 2016-06-14 22:09
Sounds like we're hot on its heels, can you replace the copycat write with a noop and still get it?

**Comment by vyzo** [comment] 2016-06-15 09:14
We should also definitely fix on a release tag -- building from master is a bad idea.

**Comment by yusefnapora** [comment] 2016-06-15 22:08
k, so after some configuration battles getting the client to run on my vagrant box....

I replaced the body of the `insertCanonical` and `updateChain` methods in `TransactorService` with this:

``` scala
Future(Transactor.MultihashReference(reference="foo"))
```

and it will still crash after about ten or so imports.

**Comment by yusefnapora** [comment] 2016-06-16 16:53
So, I've made a very simple "hello world" scala service and a python client.  When the client is running on an ubuntu vm, I can get the service to fail with the same bug after about 5 requests.

I've tried installing grpc from source, using the bugfix branch referenced in this issue: https://github.com/grpc/grpc/issues/6931

when I do that, I still get the error, but the hex dump of the first 5 bytes is different:

with grpc 0.14.0:

```
io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 0000040800
```

with grpc installed from the bugfix branch:

```
io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 0000000401
```

However, that could easily be unrelated to the bugfix, since the branch is based on 0.15.0-dev and there may have been other changes that could cause different data to be received.  I'll probably try building form the commit just prior to the fix to see what it gets.

**Comment by parkan** [comment] 2016-06-16 17:16
For those keeping track, the error message in the second case is wrong: it IS `SETTINGS`, but with an `ACK` flag, aka the wrong half of `SETTINGS-SETTINGS+ACK` exchange

**Comment by yusefnapora** [comment] 2016-06-16 18:26
Made a grpc issue for this here: https://github.com/grpc/grpc/issues/6936

**Comment by denisnazarov** [comment] 2016-06-22 21:46
This is fixed?

**Comment by yusefnapora** [comment] 2016-06-23 14:58
Yeah, this is fixed in grpc master.

**Closed as completed by yusefnapora** 2016-06-23 14:58 UTC
